---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: hub.tal.com/zhangjiyou/monitor-test:v1
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: image-pull
